CRUD_CBVs/urls.py
from django.conf.urls import url

from CRUD_CBVs import views

app_name = 'CRUD_CBVs'

urlpatterns = [
    url('', views.MovieList.as_view(), name='movie_list'),
    url(r'^new$', views.MovieCreate.as_view(), name='movie_new'),
    url(r'^edit/(?P<pk>\d+)$', views.MovieUpdate.as_view(), name='movie_edit'),
    url(r'^delete/(?P<pk>\d+)$', views.MovieDelete.as_view(), name='movie_delete'),
]

CRUD_Django_Example/urls.py
from django.conf.urls import url
from django.contrib import admin

from CRUD_FBVs import views

app_name = 'CRUD_FBVs'

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^$', views.movies_list, name='movies_list'),
    url(r'^new$', views.movies_create, name='movies_new'),
    url(r'^edit/(?P<pk>\d+)$', views.movies_update, name='movies_edit'),
    url(r'^delete/(?P<pk>\d+)$', views.movies_delete, name='movies_delete'),
]

CRUD_CBVs/models.py
# Create your models here.
from django.db import models
from django.urls import reverse


class Movie(models.Model):
    title = models.CharField(max_length=200)
    genre = models.IntegerField()

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('CRUD_CBVs:movie_edit', kwargs={'pk': self.pk})

CRUD_FBVs/models.py
# Create your models here.
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Movies(models.Model):
    '''''by specifying user as Foreign Key, we're using the builtin User model of django.'''

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    genre = models.CharField(max_length=200)

def __unicode__(self):
    return self.title


def get_absolute_url(self):
    return reverse('CRUD_FBVs:movies_edit', kwargs={'pk': self.pk})

CRUD_FBVs/forms.py
from django import forms

from .models import Movies


class MoviesForm(forms.ModelForm):
    class Meta:
        model = Movies
        fields = ['title', 'genre']

CRUD_CBVs/views.py
# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from CRUD_CBVs.models import Movie


class MovieList(ListView):
    model = Movie


class MovieCreate(CreateView):
    model = Movie
    fields = ['title', 'genre']
    success_url = reverse_lazy('CRUD_CBVs: movie_list')


class MovieUpdate(UpdateView):
    model = Movie
    fields = ['title', 'genre']
    success_url = reverse_lazy('CRUD_CBVs: movie_list')


class MovieDelete(DeleteView):
    model = Movie


success_url = reverse_lazy('CRUD_CBVs: movie_list')

CRUD_FBVs/views.py
# Create your views here.
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect

from CRUD_FBVs.models import Movies
from .forms import MoviesForm


@login_required
def movies_list(request):
    if request.user.is_superuser:
        movies = Movies.objects.all()
    else:
        movies = Movies.objects.filter(user=request.user)
    return render(request, 'movies_list.html', {
        'object_list': movies
    })


@login_required
def movies_create(request):
    form = MoviesForm(request.POST or None)

    if form.is_valid():
        movies = form.save(commit=False)
        movies.user = request.user
        movies.save()
        return redirect('CRUD_FBVs:movies_list')
    return render(request, 'movies_form.html', {'form': form})


@login_required
def movies_update(request, pk):
    if request.user.is_superuser:
        movies = get_object_or_404(Movies, pk=pk)
    else:
        movies = get_object_or_404(Movies, pk=pk, user=request.user)
    form = MoviesForm(request.POST or None, instance=movies)
    if form.is_valid():
        form.save()
        return redirect('CRUD_FBVs:movies_list')
    return render(request, 'movies_form.html', {'form': form})


@login_required
def movies_delete(request, pk):
    if request.user.is_superuser:
        movies = get_object_or_404(Movies, pk=pk)
    else:
        movies = get_object_or_404(Movies, pk=pk, user=request.user)
    if request.method == 'POST':
        movies.delete()
        return redirect('CRUD_FBVs:movies_list')
    return render(request, 'confirm_delete.html', {'object': movies})

CRUD_CBVs/templates/CRUD_CBVs/confirm_delete.html
<h1>CRUD Class Based View Example</h1>
<form method="post">
    {% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit"/>
</form>

CRUD_CBVs/templates/CRUD_CBVs/movie_form.html
<h1>CRUD Class Based View Example</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit"/>
</form>

CRUD_CBVs/templates/CRUD_CBVs/movie_list.html
<h1>CRUD Class Based View Example</h1>
<ul>
    {% for movie in object_list %}
        <li>{{ movie.title }} {{ movie.genre }}
            <a href="{% url 'CRUD_CBVs:movie_edit' movie.id %}">edit</a>
            <a href="{% url 'CRUD_CBVs:movie_delete' movie.id %}">delete</a>
        </li>
    {% endfor %}
</ul>

<a href="{% url 'CRUD_CBVs:movie_new' %}">New</a>

CRUD_FBVs/templates/confirm_delete.html
#confirm_delete.html

<h1>CRUD Function Based View Example</h1>
<form method="post">
    {% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit"/>
</form>

CRUD_FBVs/templates/movie_list.html
# movie_list.html

<h1>CRUD Function Based View Example</h1>
<ul>
    {% for movies in object_list %}
        <li>{{ movies.title }} {{ movies.genre }}
            <a href="{% url 'CRUD_FBVs:movies_edit' movies.id %}">edit</a>
            <a href="{% url 'CRUD_FBVs:movies_delete' movies.id %}">delete</a>
        </li>
    {% endfor %}
</ul>

<a href="{% url 'CRUD_FBVs:movies_new' %}">Add</a>

CRUD_FBVs/templates/movies_form.html
# movies_form.html

<h1>CRUD Function Based View Example</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit"/>
</form>